#include "inst.h"

Inst INSTRUCTIONS[0xFF + 1] = {
	[0x00] = {T_NOP, M_IMP},
	[0x01] = {T_LD, M_U16, .rd = REG_BC},
	[0x02] = {T_LD, M_MR_R, .rd = REG_BC, .rs = REG_A},
	[0x03] = {T_INC, M_R, .rd = REG_BC, .rs = REG_BC},
	[0x04] = {T_INC, M_R, .rd = REG_B, .rs = REG_B},
	[0x05] = {T_DEC, M_R, .rd = REG_B, .rs = REG_B},
	[0x06] = {T_LD, M_U8, .rd = REG_B},
	[0x07] = {T_RLCA, M_IMP},
	[0x08] = {T_LD16, M_M_U16_R, .rs = REG_SP},
	[0x09] = {T_ADD, M_R, .rd = REG_HL, .rs = REG_BC},
	[0x0A] = {T_LD, M_MR, .rd = REG_A, .rs = REG_BC},
	[0x0B] = {T_DEC, M_R, .rd = REG_BC, .rs = REG_BC},
	[0x0C] = {T_INC, M_R, .rd = REG_C, .rs = REG_C},
	[0x0D] = {T_DEC, M_R, .rd = REG_C, .rs = REG_C},
	[0x0E] = {T_LD, M_U8, .rd = REG_C},
	[0x0F] = {T_RRCA, M_IMP},

	[0x10] = {T_STOP, M_U8},
	[0x11] = {T_LD, M_U16, .rd = REG_DE},
	[0x12] = {T_LD, M_MR_R, .rd = REG_DE, .rs = REG_A},
	[0x13] = {T_INC, M_R, .rd = REG_DE, .rs = REG_DE},
	[0x14] = {T_INC, M_R, .rd = REG_D, .rs = REG_D},
	[0x15] = {T_DEC, M_R, .rd = REG_D, .rs = REG_D},
	[0x16] = {T_LD, M_U8, .rd = REG_D},
	[0x17] = {T_RLA, M_IMP},
	[0x18] = {T_JR, M_U8},
	[0x19] = {T_ADD, M_R, .rd = REG_HL, .rs = REG_DE},
	[0x1A] = {T_LD, M_MR, .rd = REG_A, .rs = REG_DE},
	[0x1B] = {T_DEC, M_R, .rd = REG_DE, .rs = REG_DE},
	[0x1C] = {T_INC, M_R, .rd = REG_E, .rs = REG_E},
	[0x1D] = {T_DEC, M_R, .rd = REG_E, .rs = REG_E},
	[0x1E] = {T_LD, M_U8, .rd = REG_E},
	[0x1F] = {T_RRA, M_IMP},

	[0x20] = {T_JR, M_U8, .cond = C_NZ},
	[0x21] = {T_LD, M_U16, .rd = REG_HL},
	[0x22] = {T_LD, M_MRI_R, .rd = REG_HL, .rs = REG_A},
	[0x23] = {T_INC, M_R, .rd = REG_HL, .rs = REG_HL},
	[0x24] = {T_INC, M_R, .rd = REG_H, .rs = REG_H},
	[0x25] = {T_DEC, M_R, .rd = REG_H, .rs = REG_H},
	[0x26] = {T_LD, M_U8, .rd = REG_H},
	[0x27] = {T_DAA, M_IMP},
	[0x28] = {T_JR, M_U8, .cond = C_Z},
	[0x29] = {T_ADD, M_R, .rd = REG_HL, .rs = REG_HL},
	[0x2A] = {T_LD, M_MRI, .rd = REG_A, .rs = REG_HL},
	[0x2B] = {T_DEC, M_R, .rd = REG_HL, .rs = REG_HL},
	[0x2C] = {T_INC, M_R, .rd = REG_L, .rs = REG_L},
	[0x2D] = {T_DEC, M_R, .rd = REG_L, .rs = REG_L},
	[0x2E] = {T_LD, M_U8, .rd = REG_L},
	[0x2F] = {T_CPL, M_IMP},

	[0x30] = {T_JR, M_U8, .cond = C_NC},
	[0x31] = {T_LD, M_U16, .rd = REG_SP},
	[0x32] = {T_LD, M_MRD_R, .rd = REG_HL, .rs = REG_A},
	[0x33] = {T_INC, M_R, .rd = REG_SP, .rs = REG_SP},
	[0x34] = {T_INC, M_MR_MR, .rd = REG_HL, .rs = REG_HL},
	[0x35] = {T_DEC, M_MR_MR, .rd = REG_HL, .rs = REG_HL},
	[0x36] = {T_LD, M_MR_U8, .rd = REG_HL},
	[0x37] = {T_SCF, M_IMP},
	[0x38] = {T_JR, M_U8, .cond = C_C},
	[0x39] = {T_ADD, M_R, .rd = REG_HL, .rs = REG_SP},
	[0x3A] = {T_LD, M_MRD, .rd = REG_A, .rs = REG_HL},
	[0x3B] = {T_DEC, M_R, .rd = REG_SP, .rs = REG_SP},
	[0x3C] = {T_INC, M_R, .rd = REG_A, .rs = REG_A},
	[0x3D] = {T_DEC, M_R, .rd = REG_A, .rs = REG_A},
	[0x3E] = {T_LD, M_U8, .rd = REG_A},
	[0x3F] = {T_CCF, M_IMP},

	[0x40] = {T_LD, M_R,  .rd = REG_B, .rs = REG_B},
	[0x41] = {T_LD, M_R,  .rd = REG_B, .rs = REG_C},
	[0x42] = {T_LD, M_R,  .rd = REG_B, .rs = REG_D},
	[0x43] = {T_LD, M_R,  .rd = REG_B, .rs = REG_E},
	[0x44] = {T_LD, M_R,  .rd = REG_B, .rs = REG_H},
	[0x45] = {T_LD, M_R,  .rd = REG_B, .rs = REG_L},
	[0x46] = {T_LD, M_MR, .rd = REG_B, .rs = REG_HL},
	[0x47] = {T_LD, M_R,  .rd = REG_B, .rs = REG_A},
	[0x48] = {T_LD, M_R,  .rd = REG_C, .rs = REG_B},
	[0x49] = {T_LD, M_R,  .rd = REG_C, .rs = REG_C},
	[0x4A] = {T_LD, M_R,  .rd = REG_C, .rs = REG_D},
	[0x4B] = {T_LD, M_R,  .rd = REG_C, .rs = REG_E},
	[0x4C] = {T_LD, M_R,  .rd = REG_C, .rs = REG_H},
	[0x4D] = {T_LD, M_R,  .rd = REG_C, .rs = REG_L},
	[0x4E] = {T_LD, M_MR, .rd = REG_C, .rs = REG_HL},
	[0x4F] = {T_LD, M_R,  .rd = REG_C, .rs = REG_A},

	[0x50] = {T_LD, M_R,  .rd = REG_D, .rs = REG_B},
	[0x51] = {T_LD, M_R,  .rd = REG_D, .rs = REG_C},
	[0x52] = {T_LD, M_R,  .rd = REG_D, .rs = REG_D},
	[0x53] = {T_LD, M_R,  .rd = REG_D, .rs = REG_E},
	[0x54] = {T_LD, M_R,  .rd = REG_D, .rs = REG_H},
	[0x55] = {T_LD, M_R,  .rd = REG_D, .rs = REG_L},
	[0x56] = {T_LD, M_MR, .rd = REG_D, .rs = REG_HL},
	[0x57] = {T_LD, M_R,  .rd = REG_D, .rs = REG_A},
	[0x58] = {T_LD, M_R,  .rd = REG_E, .rs = REG_B},
	[0x59] = {T_LD, M_R,  .rd = REG_E, .rs = REG_C},
	[0x5A] = {T_LD, M_R,  .rd = REG_E, .rs = REG_D},
	[0x5B] = {T_LD, M_R,  .rd = REG_E, .rs = REG_E},
	[0x5C] = {T_LD, M_R,  .rd = REG_E, .rs = REG_H},
	[0x5D] = {T_LD, M_R,  .rd = REG_E, .rs = REG_L},
	[0x5E] = {T_LD, M_MR, .rd = REG_E, .rs = REG_HL},
	[0x5F] = {T_LD, M_R,  .rd = REG_E, .rs = REG_A},

	[0x60] = {T_LD, M_R,  .rd = REG_H, .rs = REG_B},
	[0x61] = {T_LD, M_R,  .rd = REG_H, .rs = REG_C},
	[0x62] = {T_LD, M_R,  .rd = REG_H, .rs = REG_D},
	[0x63] = {T_LD, M_R,  .rd = REG_H, .rs = REG_E},
	[0x64] = {T_LD, M_R,  .rd = REG_H, .rs = REG_H},
	[0x65] = {T_LD, M_R,  .rd = REG_H, .rs = REG_L},
	[0x66] = {T_LD, M_MR, .rd = REG_H, .rs = REG_HL},
	[0x67] = {T_LD, M_R,  .rd = REG_H, .rs = REG_A},
	[0x68] = {T_LD, M_R,  .rd = REG_L, .rs = REG_B},
	[0x69] = {T_LD, M_R,  .rd = REG_L, .rs = REG_C},
	[0x6A] = {T_LD, M_R,  .rd = REG_L, .rs = REG_D},
	[0x6B] = {T_LD, M_R,  .rd = REG_L, .rs = REG_E},
	[0x6C] = {T_LD, M_R,  .rd = REG_L, .rs = REG_H},
	[0x6D] = {T_LD, M_R,  .rd = REG_L, .rs = REG_L},
	[0x6E] = {T_LD, M_MR, .rd = REG_L, .rs = REG_HL},
	[0x6F] = {T_LD, M_R,  .rd = REG_L, .rs = REG_A},

	[0x70] = {T_LD, M_MR_R, .rd = REG_HL, .rs = REG_B},
	[0x71] = {T_LD, M_MR_R, .rd = REG_HL, .rs = REG_C},
	[0x72] = {T_LD, M_MR_R, .rd = REG_HL, .rs = REG_D},
	[0x73] = {T_LD, M_MR_R, .rd = REG_HL, .rs = REG_E},
	[0x74] = {T_LD, M_MR_R, .rd = REG_HL, .rs = REG_H},
	[0x75] = {T_LD, M_MR_R, .rd = REG_HL, .rs = REG_L},
	[0x76] = {T_HALT, M_IMP},
	[0x77] = {T_LD, M_MR_R, .rd = REG_HL, .rs = REG_A},
	[0x78] = {T_LD, M_R, .rd = REG_A, .rs = REG_B},
	[0x79] = {T_LD, M_R, .rd = REG_A, .rs = REG_C},
	[0x7A] = {T_LD, M_R, .rd = REG_A, .rs = REG_D},
	[0x7B] = {T_LD, M_R, .rd = REG_A, .rs = REG_E},
	[0x7C] = {T_LD, M_R, .rd = REG_A, .rs = REG_H},
	[0x7D] = {T_LD, M_R, .rd = REG_A, .rs = REG_L},
	[0x7E] = {T_LD, M_MR, .rd = REG_A, .rs = REG_HL},
	[0x7F] = {T_LD, M_R, .rd = REG_A, .rs = REG_A},

	[0x80] = {T_ADD, M_R, .rd = REG_A, .rs = REG_B},
	[0x81] = {T_ADD, M_R, .rd = REG_A, .rs = REG_C},
	[0x82] = {T_ADD, M_R, .rd = REG_A, .rs = REG_D},
	[0x83] = {T_ADD, M_R, .rd = REG_A, .rs = REG_E},
	[0x84] = {T_ADD, M_R, .rd = REG_A, .rs = REG_H},
	[0x85] = {T_ADD, M_R, .rd = REG_A, .rs = REG_L},
	[0x86] = {T_ADD, M_MR, .rd = REG_A, .rs = REG_HL},
	[0x87] = {T_ADD, M_R, .rd = REG_A, .rs = REG_A},
	[0x88] = {T_ADC, M_R, .rd = REG_A, .rs = REG_B},
	[0x89] = {T_ADC, M_R, .rd = REG_A, .rs = REG_C},
	[0x8A] = {T_ADC, M_R, .rd = REG_A, .rs = REG_D},
	[0x8B] = {T_ADC, M_R, .rd = REG_A, .rs = REG_E},
	[0x8C] = {T_ADC, M_R, .rd = REG_A, .rs = REG_H},
	[0x8D] = {T_ADC, M_R, .rd = REG_A, .rs = REG_L},
	[0x8E] = {T_ADC, M_MR, .rd = REG_A, .rs = REG_HL},
	[0x8F] = {T_ADC, M_R, .rd = REG_A, .rs = REG_A},

	[0x90] = {T_SUB, M_R, .rd = REG_A, .rs = REG_B},
	[0x91] = {T_SUB, M_R, .rd = REG_A, .rs = REG_C},
	[0x92] = {T_SUB, M_R, .rd = REG_A, .rs = REG_D},
	[0x93] = {T_SUB, M_R, .rd = REG_A, .rs = REG_E},
	[0x94] = {T_SUB, M_R, .rd = REG_A, .rs = REG_H},
	[0x95] = {T_SUB, M_R, .rd = REG_A, .rs = REG_L},
	[0x96] = {T_SUB, M_MR, .rd = REG_A, .rs = REG_HL},
	[0x97] = {T_SUB, M_R, .rd = REG_A, .rs = REG_A},
	[0x98] = {T_SBC, M_R, .rd = REG_A, .rs = REG_B},
	[0x99] = {T_SBC, M_R, .rd = REG_A, .rs = REG_C},
	[0x9A] = {T_SBC, M_R, .rd = REG_A, .rs = REG_D},
	[0x9B] = {T_SBC, M_R, .rd = REG_A, .rs = REG_E},
	[0x9C] = {T_SBC, M_R, .rd = REG_A, .rs = REG_H},
	[0x9D] = {T_SBC, M_R, .rd = REG_A, .rs = REG_L},
	[0x9E] = {T_SBC, M_MR, .rd = REG_A, .rs = REG_HL},
	[0x9F] = {T_SBC, M_R, .rd = REG_A, .rs = REG_A},

	[0xA0] = {T_AND, M_R, .rd = REG_A, .rs = REG_B},
	[0xA1] = {T_AND, M_R, .rd = REG_A, .rs = REG_C},
	[0xA2] = {T_AND, M_R, .rd = REG_A, .rs = REG_D},
	[0xA3] = {T_AND, M_R, .rd = REG_A, .rs = REG_E},
	[0xA4] = {T_AND, M_R, .rd = REG_A, .rs = REG_H},
	[0xA5] = {T_AND, M_R, .rd = REG_A, .rs = REG_L},
	[0xA6] = {T_AND, M_MR, .rd = REG_A, .rs = REG_HL},
	[0xA7] = {T_AND, M_R, .rd = REG_A, .rs = REG_A},
	[0xA8] = {T_XOR, M_R, .rd = REG_A, .rs = REG_B},
	[0xA9] = {T_XOR, M_R, .rd = REG_A, .rs = REG_C},
	[0xAA] = {T_XOR, M_R, .rd = REG_A, .rs = REG_D},
	[0xAB] = {T_XOR, M_R, .rd = REG_A, .rs = REG_E},
	[0xAC] = {T_XOR, M_R, .rd = REG_A, .rs = REG_H},
	[0xAD] = {T_XOR, M_R, .rd = REG_A, .rs = REG_L},
	[0xAE] = {T_XOR, M_MR, .rd = REG_A, .rs = REG_HL},
	[0xAF] = {T_XOR, M_R, .rd = REG_A, .rs = REG_A},

	[0xB0] = {T_OR, M_R, .rd = REG_A, .rs = REG_B},
	[0xB1] = {T_OR, M_R, .rd = REG_A, .rs = REG_C},
	[0xB2] = {T_OR, M_R, .rd = REG_A, .rs = REG_D},
	[0xB3] = {T_OR, M_R, .rd = REG_A, .rs = REG_E},
	[0xB4] = {T_OR, M_R, .rd = REG_A, .rs = REG_H},
	[0xB5] = {T_OR, M_R, .rd = REG_A, .rs = REG_L},
	[0xB6] = {T_OR, M_MR, .rd = REG_A, .rs = REG_HL},
	[0xB7] = {T_OR, M_R, .rd = REG_A, .rs = REG_A},
	[0xB8] = {T_CP, M_R, .rd = REG_A, .rs = REG_B},
	[0xB9] = {T_CP, M_R, .rd = REG_A, .rs = REG_C},
	[0xBA] = {T_CP, M_R, .rd = REG_A, .rs = REG_D},
	[0xBB] = {T_CP, M_R, .rd = REG_A, .rs = REG_E},
	[0xBC] = {T_CP, M_R, .rd = REG_A, .rs = REG_H},
	[0xBD] = {T_CP, M_R, .rd = REG_A, .rs = REG_L},
	[0xBE] = {T_CP, M_MR, .rd = REG_A, .rs = REG_HL},
	[0xBF] = {T_CP, M_R, .rd = REG_A, .rs = REG_A},

	[0xC0] = {T_RET, M_IMP, .cond = C_NZ},
	[0xC1] = {T_POP, M_IMP, .rd = REG_BC},
	[0xC2] = {T_JP, M_U16, .cond = C_NZ},
	[0xC3] = {T_JP, M_U16},
	[0xC4] = {T_CALL, M_U16, .cond = C_NZ},
	[0xC5] = {T_PUSH, M_R, .rs = REG_BC},
	[0xC6] = {T_ADD, M_U8, .rd = REG_A},
	[0xC7] = {T_RST, M_IMP, .num = 0},
	[0xC8] = {T_RET, M_IMP, .cond = C_Z},
	[0xC9] = {T_RET, M_IMP},
	[0xCA] = {T_JP, M_U16, .cond = C_Z},
	[0xCB] = {T_CB, M_U8},
	[0xCC] = {T_CALL, M_U16, .cond = C_Z},
	[0xCD] = {T_CALL, M_U16},
	[0xCE] = {T_ADC, M_U8, .rd = REG_A},
	[0xCF] = {T_RST, M_IMP, .num = 1},

	[0xD0] = {T_RET, M_IMP, .cond = C_NC},
	[0xD1] = {T_POP, M_IMP, .rd = REG_DE},
	[0xD2] = {T_JP, M_U16, .cond = C_NC},
	[0xD4] = {T_CALL, M_U16, .cond = C_NC},
	[0xD5] = {T_PUSH, M_R, .rs = REG_DE},
	[0xD6] = {T_SUB, M_U8, .rd = REG_A},
	[0xD7] = {T_RST, M_IMP, .num = 2},
	[0xD8] = {T_RET, M_IMP, .cond = C_C},
	[0xD9] = {T_RETI, M_IMP},
	[0xDA] = {T_JP, M_U16, .cond = C_C},
	[0xDC] = {T_CALL, M_U16, .cond = C_C},
	[0xDE] = {T_SBC, M_U8, .rd = REG_A},
	[0xDF] = {T_RST, M_IMP, .num = 3},

	[0xE0] = {T_LD, M_M_U8, .rs = REG_A},
	[0xE1] = {T_POP, M_IMP, .rd = REG_HL},
	[0xE2] = {T_LD, M_MR8_R, .rd = REG_C, .rs = REG_A},
	[0xE5] = {T_PUSH, M_R, .rs = REG_HL},
	[0xE6] = {T_AND, M_U8, .rd = REG_A},
	[0xE7] = {T_RST, M_IMP, .num = 4},
	[0xE8] = {T_ADD, M_U8, .rd = REG_SP},
	[0xE9] = {T_JP, M_R, .rs = REG_HL},
	[0xEA] = {T_LD, M_M_U16_R, .rs = REG_A},
	[0xEE] = {T_XOR, M_U8, .rd = REG_A},
	[0xEF] = {T_RST, M_IMP, .num = 5},

	[0xF0] = {T_LD, M_R_M_U8, .rd = REG_A},
	[0xF1] = {T_POP, M_IMP, .rd = REG_AF},
	[0xF2] = {T_LD, M_MR8, .rd = REG_A, .rs = REG_C},
	[0xF3] = {T_DI, M_IMP},
	[0xF5] = {T_PUSH, M_R, .rs = REG_AF},
	[0xF6] = {T_OR, M_U8, .rd = REG_A},
	[0xF7] = {T_RST, M_IMP, .num = 6},
	[0xF8] = {T_LD, M_SP_I8, .rd = REG_HL},
	[0xF9] = {T_LD, M_R, .rd = REG_SP, .rs = REG_HL},
	[0xFA] = {T_LD, M_R_M_U16, .rd = REG_A},
	[0xFB] = {T_EI, M_IMP},
	[0xFE] = {T_CP, M_U8, .rd = REG_A},
	[0xFF] = {T_RST, M_IMP, .num = 7}
};
