#ifndef CRESCENT_POSIX_SYSCALLS_H
#define CRESCENT_POSIX_SYSCALLS_H

typedef enum CrescentPosixSyscall {
	SYS_POSIX_MMAP = 0x1000,
	SYS_POSIX_MUNMAP,
	SYS_POSIX_MPROTECT,

	SYS_POSIX_SIGPROCMASK,
	SYS_POSIX_SIGACTION,
	SYS_POSIX_SIGRESTORE,
	SYS_POSIX_TGKILL,
	SYS_POSIX_KILL,

	SYS_POSIX_PPOLL,
	SYS_POSIX_IOCTL,
	SYS_POSIX_FCNTL
} CrescentPosixSyscall;

#endif
