#ifndef CRESCENT_SYSCALLS_H
#define CRESCENT_SYSCALLS_H
#include <stddef.h>

typedef size_t CrescentHandle;

typedef struct {
	const char* str;
	size_t len;
} CrescentStringView;

#define INVALID_CRESCENT_HANDLE ((CrescentHandle) -1)

typedef enum {
	SYS_THREAD_CREATE,
	SYS_THREAD_EXIT,

	SYS_PROCESS_CREATE,
	SYS_PROCESS_EXIT,

	SYS_KILL,
	SYS_GET_STATUS,

	SYS_SLEEP,

	SYS_SYSLOG,
	SYS_DEVLINK,
	SYS_CLOSE_HANDLE,

	SYS_MAP,
	SYS_UNMAP,

	SYS_POLL_EVENT,

	SYS_SHUTDOWN,

	SYS_SERVICE_CREATE,
	SYS_SERVICE_GET,

	SYS_SOCKET_CREATE,
	SYS_SOCKET_CONNECT,
	SYS_SOCKET_LISTEN,
	SYS_SOCKET_ACCEPT,
	SYS_SOCKET_SEND,
	SYS_SOCKET_RECEIVE
} CrescentSyscall;

typedef enum {
	ERR_MAX = -0x1000,
	ERR_INVALID_ARGUMENT,
	ERR_UNSUPPORTED,
	ERR_FAULT,
	ERR_NO_MEM,
	ERR_BUFFER_TOO_SMALL,
	ERR_TRY_AGAIN,
	ERR_ALREADY_EXISTS,
	ERR_NOT_EXISTS,
} CrescentError;

typedef enum {
	SHUTDOWN_TYPE_POWER_OFF,
	SHUTDOWN_TYPE_REBOOT
} ShutdownType;

#define CRESCENT_PROT_READ (1U << 0)
#define CRESCENT_PROT_WRITE (1U << 1)
#define CRESCENT_PROT_EXEC (1U << 2)

#endif
