#include "crescent/input.h"
#include "types.h"

// clang-format off

const char* layout_fi[(usize) SCAN_MAX] = {
	[SCAN_A]                        = "A",
	[SCAN_B]                        = "B",
	[SCAN_C]                        = "C",
	[SCAN_D]                        = "D",
	[SCAN_E]                        = "E",
	[SCAN_F]                        = "F",
	[SCAN_G]                        = "G",
	[SCAN_H]                        = "H",
	[SCAN_I]                        = "I",
	[SCAN_J]                        = "J",
	[SCAN_K]                        = "K",
	[SCAN_L]                        = "L",
	[SCAN_M]                        = "M",
	[SCAN_N]                        = "N",
	[SCAN_O]                        = "O",
	[SCAN_P]                        = "P",
	[SCAN_Q]                        = "Q",
	[SCAN_R]                        = "R",
	[SCAN_S]                        = "S",
	[SCAN_T]                        = "T",
	[SCAN_U]                        = "U",
	[SCAN_V]                        = "V",
	[SCAN_W]                        = "W",
	[SCAN_X]                        = "X",
	[SCAN_Y]                        = "Y",
	[SCAN_Z]                        = "Z",
	[SCAN_1]                        = "1",
	[SCAN_2]                        = "2",
	[SCAN_3]                        = "3",
	[SCAN_4]                        = "4",
	[SCAN_5]                        = "5",
	[SCAN_6]                        = "6",
	[SCAN_7]                        = "7",
	[SCAN_8]                        = "8",
	[SCAN_9]                        = "9",
	[SCAN_0]                        = "0",
	[SCAN_ENTER]                    = "\n",
	[SCAN_ESC]                      = "",
	[SCAN_BACKSPACE]                = "\b",
	[SCAN_TAB]                      = "\t",
	[SCAN_SPACE]                    = " ",
	[SCAN_MINUS]                    = "+",
	[SCAN_EQUAL]                    = "´",
	[SCAN_LBRACKET]                 = "å",
	[SCAN_RBRACKET]                 = "¨",
	[SCAN_BACKSLASH]                = "'",
	[SCAN_NON_US_HASH]              = "#",
	[SCAN_SEMICOLON]                = "ä",
	[SCAN_APOSTROPHE]               = "ö",
	[SCAN_GRAVE]                    = "§",
	[SCAN_COMMA]                    = ",",
	[SCAN_DOT]                      = ".",
	[SCAN_SLASH]                    = "-",
	[SCAN_KEYPAD_SLASH]             = "/",
	[SCAN_KEYPAD_STAR]              = "*",
	[SCAN_KEYPAD_MINUS]             = "-",
	[SCAN_KEYPAD_PLUS]              = "+",
	[SCAN_KEYPAD_ENTER]             = "\n",
	[SCAN_KEYPAD_1]                 = "1",
	[SCAN_KEYPAD_2]                 = "2",
	[SCAN_KEYPAD_3]                 = "3",
	[SCAN_KEYPAD_4]                 = "4",
	[SCAN_KEYPAD_5]                 = "5",
	[SCAN_KEYPAD_6]                 = "6",
	[SCAN_KEYPAD_7]                 = "7",
	[SCAN_KEYPAD_8]                 = "8",
	[SCAN_KEYPAD_9]                 = "9",
	[SCAN_KEYPAD_0]                 = "0",
	[SCAN_KEYPAD_DOT]               = ".",
	[SCAN_NON_US_BACKSLASH]         = "\\",
};

// clang-format on