name: It Compiles!
on: [push, workflow_dispatch]
jobs:
  Compile:
    runs-on: ubuntu-latest
    #container: archlinux:latest
    container: ubuntu:rolling
    steps:
      - name: Install dependencies
        #run: >
        #  pacman -Sy --noconfirm --needed glibc clang nasm lld cmake ninja xorriso git parted
        run: >
          apt-get update && apt-get install clang lld cmake ninja-build xorriso git parted -y
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure source
        run: >
          cmake -B build -G Ninja 
          -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .
      - name: Build
        run: ninja -C build
