name: It Compiles!
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install dependencies
        run: >
          pacman -Sy --noconfirm --needed clang nasm lld cmake ninja xorriso git
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure source
        run: >
          cmake -B build -G Ninja 
          -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .
      - name: Build
        run: ninja -C build