name: It Compiles!
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Disable initramfs update
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
      - name: Disable man-db update
        run: sudo rm -f /var/lib/man-db/auto-update

      - name: Install llvm
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo rm -f $(which clang) $(which clang++)
          sudo rm -f /usr/bin/clang /usr/bin/clang++
          sudo ln -s $(which clang-19) /usr/bin/clang
          sudo ln -s $(which clang++-19) /usr/bin/clang++
          sudo ln -s $(which llvm-objcopy-19) /usr/bin/llvm-objcopy

      - name: Install qpkg
        run: |
          wget https://github.com/Qwinci/qpkg/releases/latest/download/qpkg-x86_64-unknown-linux-musl.tar.gz
          tar -xf qpkg-x86_64-unknown-linux-musl.tar.gz
          sudo mv qpkg /usr/bin

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install make cmake ninja-build acpica-tools git -y

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'Qwinci/crescent-bootstrap'
          submodules: true

      - name: Build (x86_64)
        run: |
          make

      - name: Build (Aarch64)
        run: |
          make ARCH=aarch64

